POST http://localhost:3005/note


###

GET http://localhost:3005/note

###

GET http://localhost:3005/note/699dedf6d9bf3d1dbc688ade

###
PUT http://localhost:3005/note/699ef55e72483c3f92b274e3
content-type: application/json

{
    "title": "hello!! again",
    "content": "hello from content"
}


###

GET http://localhost:3010/note/699ef55e72483c3f92b274e3?analysis=true