POST http://localhost:3000/note
Content-Type: application/json

{
    "title": "title1234",
    "content": "Ignorant saw her her drawings marriage laughter. Case oh an that or away sigh do here upon. Acuteness you exquisite ourselves now end forfeited. Enquire ye without it garrets up himself. Interest our nor received followed was. Cultivated an up solicitude mr unpleasant. "
}

###

GET http://localhost:3000/note

###

GET http://localhost:3000/note/699dedf6d9bf3d1dbc688ade